[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 80

[tool.mypy]
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true

[tool.pytest.ini_options]
minversion = "7.0"
